language: node_js

sudo: false

cache:
  apt: true,
  directories: 
    -node_modules

nodejs: stable

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../

script:
  - npm test